# Generated by Django 3.1.3 on 2020-11-16 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('content', models.TextField()),
                ('file_type', models.CharField(choices=[('sty', 'package'), ('cls', 'class'), ('tex', 'ordinary .tex')], default='tex', max_length=3)),
                ('is_part_of_folder', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.folder')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.template'),
        ),
    ]
