# Generated by Django 3.1.3 on 2020-11-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefile',
            name='is_part_of_folder',
        ),
    ]
