# Generated by Django 3.1.3 on 2020-11-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_templatefile_is_part_of_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefile',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.template'),
        ),
    ]
