# Generated by Django 3.1.3 on 2020-11-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_templatefile_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
