# Generated by Django 3.1.3 on 2020-11-16 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201116_2245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateFile',
            new_name='File',
        ),
    ]
